#!/usr/bin/env bash
# DropSites v1.0 Release Runbook
# Run each step manually and verify before proceeding to the next.
set -e

echo "=== DropSites v1.0 Release Runbook ==="
echo ""
echo "Step 0: Pre-flight checks"
echo "  [ ] All tests pass: pnpm test && pnpm playwright test"
echo "  [ ] Zero open P0/P1 bugs in beta feedback"
echo "  [ ] Pentest sign-off recorded in docs/security/"
echo "  [ ] Changelog updated: docs/changelog/v1.0.md"
echo "  [ ] README updated with MCP section"
echo ""
echo "Step 1: Tag release"
echo "  git tag v1.0.0"
echo "  git push origin v1.0.0"
echo ""
echo "Step 2: Publish npm packages"
echo "  pnpm --filter @dropsites/sdk build && pnpm --filter @dropsites/sdk publish --access public"
echo "  pnpm --filter @dropsites/mcp build && pnpm --filter @dropsites/mcp publish --access public"
echo ""
echo "Step 3: Deploy to production"
echo "  # Follow docs/deployment/production-checklist.md"
echo ""
echo "Step 4: Post announcement blog"
echo "  # Verify https://dropsites.app/blog/mcp-launch is live"
echo ""
echo "Step 5: Community announcements"
echo "  [ ] Post to Twitter/X: 'DropSites v1.0 is live. Deploy static sites from Claude Desktop. @dropsites/mcp on npm.'"
echo "  [ ] Post to Hacker News Show HN"
echo "  [ ] Post to relevant Discord/Slack communities"
echo ""
echo "=== Release complete ==="
